task_specification: |
  Read the last question carefully and think step by step before answering, the final answer must be only a number. You are a math tutor who helps students of all levels understand and solve mathematical problems.
parser_prompt:
  text: |
    Extract the following response final answer, only number with no symbol no comma or full stop, only the numeric value. DO NOT OUTPUT ANYTHING ELSE OTHER THAN THE FINAL ANSWER NUMBER!
    Response: 
  json: |
    Convert the following response into a valid JSON with ``` bracket enclosed
    The payload should only contain 2 keys : reason, answer
    The JSON format must follow this format:
    ```
    {
      "reason": "requirement: valid JSON string here, make sure to escape everything",
      "answer": "requirement: only number with no symbol no comma or full stop, only the numeric value."
    }
    ```
    Note: In the answer field DO NOT OUTPUT ANYTHING ELSE OTHER THAN THE FINAL ANSWER NUMBER
    Response:
  xml: |
    Convert the following response into a valid XML with ``` bracket enclosed
    The payload should only contain 2 keys : reason, answer
    The XML format must follow this format:
    ```
    <root>
      <reason>...</reason>
      <answer>...</answer>
    </root>
    ```
    requirement: 
    - valid XML string in <reason> </reason> block, make sure to escape everything
    - <answer>...</answer> should only contain one number with no symbol no comma or full stop
    Note: In the answer field DO NOT OUTPUT ANYTHING ELSE OTHER THAN THE FINAL ANSWER NUMBER
    Response:
  yaml: |
    Convert the following response into a valid YAML with ``` bracket enclosed
    The payload should only contain 2 keys : reason, answer
    The YAML format must follow this format:
    ```
    reason: |
      ...
    answer: ...
    ```
    requirement: 
    - valid YAML string in reason block, make sure to escape everything that break YAML format, becareful of tab
    - answer value should only contain one number with no symbol no comma or full stop
    Note: In the answer field DO NOT OUTPUT ANYTHING ELSE OTHER THAN THE FINAL ANSWER NUMBER
    Response:
format_instruct:
  text: |
    Answer in natural language text with think step by step
  json: |
    Answer in JSON format with think step by step
  yaml: |
    Answer in YAML format with think step by step
  xml: |
    Answer in XML format with think step by step
fewshots:
  - question: "There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?"
    response:
      reason: "There are 15 trees originally. Then there were 21 trees after some more were planted. So there must have been 21 - 15 = 6."
      answer: "6"
  - question: "If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?"
    response:
      reason: "There are originally 3 cars. 2 more cars arrive. 3 + 2 = 5."
      answer: "5"
  - question: "Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?"
    response:
      reason: "Originally, Leah had 32 chocolates. Her sister had 42. So in total they had 32 + 42 = 74. After eating 35, they had 74 - 35 = 39."
      answer: "39"
  - question: "Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?"
    response:
      reason: "Jason started with 20 lollipops. Then he had 12 after giving some to Denny. So he gave Denny 20 - 12 = 8."
      answer: "8"
  - question: "Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now?"
    response:
      reason: "Shawn started with 5 toys. If he got 2 toys each from his mom and dad, then that is 4 more toys. 5 + 4 = 9."
      answer: "9"
  - question: "There were nine computers in the server room. Five more computers were installed each day, from monday to thursday. How many computers are now in the server room?"
    response:
      reason: "There were originally 9 computers. For each of 4 days, 5 more computers were added. So 5 * 4 = 20 computers were added. 9 + 20 is 29."
      answer: "29"
  - question: "Michael had 58 golf balls. On tuesday, he lost 23 golf balls. On wednesday, he lost 2 more. How many golf balls did he have at the end of wednesday?"
    response:
      reason: "Michael started with 58 golf balls. After losing 23 on tuesday, he had 58 - 23 = 35. After losing 2 more, he had 35 - 2 = 33 golf balls."
      answer: "33"
  - question: "Olivia has $23. She bought five bagels for $3 each. How much money does she have left?"
    response:
      reason: "Olivia had 23 dollars. 5 bagels for 3 dollars each will be 5 x 3 = 15 dollars. So she has 23 - 15 dollars left. 23 - 15 is 8."
      answer: "8"
