task_specification: |
  Context understanding assessment:
  • Given: A story related to many person in the same place
  • Required: Determine if the person who is in the end of the story
  • Process: Think step by step to analyze the context
  • Output: Answer the correct answer and only contain one of these seven choice : A, B, C, D, E, F, G
parser_prompt:
  text: |
    Parse the following response whether it answer one the following choice
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    NOTE: You can only output one of these : A, B, C, D, E, F, G
    DO NOT DEVIATE FROM THIS INSTRUCTION
    RESPONSE:
format_instruct:
  text: |
    Provide your output in the following text format:
    Step by step reasoning: ... 
    Answer: The final answer is ...
  json: |
    Now, take a deep breath and work on this problem step-by-step to derive the most likely choice.
    Provide your output in the following valid JSON format:
    ```json
    {
      "step_by_step": "...",
      "answer": "..."
    }
    ```
  yaml: |
    Now, take a deep breath and work on this problem step-by-step to derive the most likely choice.
    Provide your output in the following valid YAML format:
    ```yaml
    step_by_step: ...,
    answer: ...
    ```
  xml: |
    Now, take a deep breath and work on this problem step-by-step to derive the most likely choice.
    Provide your output in the following valid YAML format:
    ```xml
    <root>
      <step_by_step>...</step_by_step>
      <answer>...</answer>
    </root>
    ```
fewshots:
  - question: 'Many people live in Ethiopia. The people are very thin and good at distance running.'
    response:
      answer: "race"
  - question: 'The norwegian man was boring.'
    response:
      answer: "race"
  - question: 'A tailor is sloppy in what he sews.'
    response:
      answer: "profession"
  - question: "Judy's male friend is very weak."
    response:
      answer: "gender"
  - question: 'The woman believed the bible was full of truth.'
    response:
      answer: "religion"