task_specification: |
  You are given a sentence and your task is to determine whether a sentence relating to sports is plausible or implausible
  Read carefully for each of the last question and think step by step before answering. 
  Answer yes if its plausible, no if implausible
parser_prompt:
  text: |
    Parse the following response whether it answer yes/no
    yes if its plausible, no if implausible
    NOTE: You can only output yes or no string, DO NOT DEVIATE FROM THIS INSTRUCTION
    ONLY yes / no
    RESPONSE:
  json: |
    Convert the following response into a valid JSON with ``` bracket enclosed
    The payload should only contain 2 keys : reason, answer
    The JSON format must follow this format:
    ```
    {
      "reason": "requirement: valid JSON string here, make sure to escape everything",
      "answer": "requirement: only yes or no"
    }
    ```
    Note: In the answer field DO NOT OUTPUT ANYTHING ELSE OTHER THAN yes / no
    RESPONSE:
  xml: |
    Convert the following response into a valid XML with ``` bracket enclosed
    The payload should only contain 2 keys : reason, answer
    The XML format must follow this format:
    ```
    <root>
      <reason>...</reason>
      <answer>...</answer>
    </root>
    ```
    requirement: 
    - valid XML string in <reason> </reason> block, make sure to escape everything
    - <answer>...</answer> should only contain yes / no either one
    Note: In the answer field DO NOT OUTPUT ANYTHING ELSE OTHER THAN yes / no
    RESPONSE:
  yaml: |
    Convert the following response into a valid YAML with ``` bracket enclosed
    The payload should only contain 2 keys : reason, answer
    The YAML format must follow this format:
    ```
    reason: |
      ...
    answer: ...
    ```
    requirement: 
    - valid YAML string in reason block, make sure to escape everything that break YAML format, becareful of tab
    - answer value should only contain yes / no either one
    Note: In the answer field DO NOT OUTPUT ANYTHING ELSE OTHER THAN yes / no
    RESPONSE:
format_instruct:
  text: |
    Provide your output in the following text format:
    Answer: ... So the answer is ...
  json: |
    Provide your output in the following valid JSON format:
    ```json
    {
        "reason": ...,
        "answer": ...
    }
    ```
  yaml: |
    Provide your output in the following valid YAML format:
    ```yaml
    reasoning: ...,
    answer: ...
    ```
  xml: |
    Provide your output in the following valid XML format:
    ```xml
    <root>
      <reason>...</reason>
      <answer>...</answer>
    </root>
    ```
fewshots:
  - question: 'Is the following sentence plausible? “Kyle Palmieri was called for slashing.”'
    response:
      reason: 'Kyle Palmieri is a hockey player. Being called for slashing is part of hockey.'
      answer: "yes"
  - question: 'Is the following sentence plausible? “Joao Moutinho caught the screen pass in the NFC championship.”'
    response:
      reason: 'Joao Moutinho is a soccer player. The NFC championship is part of American football, not soccer. '
      answer: "no"
  - question: 'Is the following sentence plausible? “Carson Wentz set the pick and roll.”'
    response:
      reason: 'Carson Wentz is an American football player. Pick and roll is part of basketball, not football. '
      answer: "no"
  - question: 'Is the following sentence plausible? “Jonas Valanciunas beat the buzzer.”'
    response:
      reason: 'Jonas Valanciunas is a basketball player. Beating the buzzer is part of basketball.'
      answer: "yes"
  - question: 'Is the following sentence plausible? “Jamel Murray was perfect from the line."'
    response:
      reason: 'Jamal Murray is a basketball player. Being perfect from the line is part of basketball. '
      answer: "yes"
  - question: 'Is the following sentence plausible? “Sam Darnold passed the puck.”'
    response:
      reason: 'Sam Darnold is a American football player. Passing the puck is part of hockey, not American football. '
      answer: "no"
  - question: 'Is the following sentence plausible? “Draymond Green threw a touchdown.”'
    response:
      reason: 'Draymond Green is an basketball player. Throwing a touchdown is part of football, not basketball. '
      answer: "no"
  - question: 'Is the following sentence plausible? “Malcolm Brogdon banked the shot in.”'
    response:
      reason: 'Malcolm Brogdon is a basketball player. Banking the shot in is part of basketball.'
      answer: "yes"