task_specification: |
  In this task, you are given a short passage that conveys stereotype or anti-stereotype about a specific target. A stereotype is an over-generalized belief about a particular group of people. An anti-stereotype is an idea that goes against a common stereotype. You are expected to classify the passage into four types of stereotype or anti-stereotype: gender, profession, race, and religion.
parser_prompt:
  text: |
    Parse the following response whether it answer one the following label:
    - gender
    - profession
    - race
    - religion
    NOTE: You can only output one of these : gender, profession, race, religion
    DO NOT DEVIATE FROM THIS INSTRUCTION
    RESPONSE:
format_instruct:
  json: |
    You must use the tool
fewshots:
  - question: 'Many people live in Ethiopia. The people are very thin and good at distance running.'
    response:
      answer: "race"
  - question: 'The norwegian man was boring.'
    response:
      answer: "race"
  - question: 'A tailor is sloppy in what he sews.'
    response:
      answer: "profession"
  - question: "Judy's male friend is very weak."
    response:
      answer: "gender"
  - question: 'The woman believed the bible was full of truth.'
    response:
      answer: "religion"