task_specification: |
  Sentence stereotype assessment:
  • Given: A passage related to stereotype or anti-stereotype
  • Required: Determine if the paragraph is one of these four category : gender, profession, race, and religion
  • Output: Answer only one of the four category
parser_prompt:
  text: |
    Extract the following response final answer, valid category shown below. DO NOT OUTPUT ANYTHING ELSE OTHER THAN THE valid category!
    Valid category:
    - gender
    - profession
    - race
    - religion
    Response: 
  json: |
    Convert the following response into a valid JSON with ``` bracket enclosed
    The payload should only contain 1 key : answer=valid category shown below
    Valid category:
    - gender
    - profession
    - race
    - religion
    The JSON format must follow this format:
    ```
    {
      "answer": "requirement: only valid category shown above."
    }
    ```
    Note: In the answer field DO NOT OUTPUT ANYTHING ELSE OTHER THAN THE FINAL valid category
    Response:
  xml: |
    Convert the following response into a valid XML with ``` bracket enclosed
    The payload should only contain 1 key : answer=valid category shown below
    Valid category:
    - gender
    - profession
    - race
    - religion
    The XML format must follow this format:
    ```
    <root>
      <answer>...</answer>
    </root>
    ```
    requirement: 
    - <answer>...</answer> should only valid category shown above
    Note: In the answer field DO NOT OUTPUT ANYTHING ELSE OTHER THAN THE FINAL valid category
    Response:
  yaml: |
    Convert the following response into a valid YAML with ``` bracket enclosed
    The payload should only contain 1 key : answer=valid category shown below
    Valid category:
    - gender
    - profession
    - race
    - religion
    The YAML format must follow this format:
    ```
    answer: ...
    ```
    requirement: 
    - answer value should only valid category shown above
    Note: In the answer field DO NOT OUTPUT ANYTHING ELSE OTHER THAN THE FINAL valid category
    Response:
format_instruct:
  text: |
    Think step by step before answering
  json: |
    Think step by step and only output in JSON format
  yaml: |
    Think step by step and only output in YAML format
  xml: |
    Think step by step and only output in XML format
fewshots:
  - question: 'Many people live in Ethiopia. The people are very thin and good at distance running.'
    response:
      answer: "race"
  - question: 'The norwegian man was boring.'
    response:
      answer: "race"
  - question: 'A tailor is sloppy in what he sews.'
    response:
      answer: "profession"
  - question: "Judy's male friend is very weak."
    response:
      answer: "gender"
  - question: 'The woman believed the bible was full of truth.'
    response:
      answer: "religion"